### ISSUE TITLE
[🐞] length parameter not working

### ISSUE THREAD

**Issue by retani** [opa-oz/emoji-hash#24]
**Describe the bug**
`getHash()` with given `length` parameter should generate a **number** of emojis according to the value of `length`. Instead it only generates **one** emoji, regardless of the length parameter. The generated emoji equals to the first emoji when no `length` parameter given.

**To Reproduce**
see example: https://codepen.io/Retani/pen/RwewpgG

**Expected behavior**
`getHash("Hello, world", {length: 3})` should generate 3 emojis

**Screenshots**
![image](https://user-images.githubusercontent.com/3465427/230339244-934e6d6b-43cf-4577-af9d-a176ad0c7889.png)

**Env (please complete the following information):**
- Browsers: Chrome, Safari, Firefox
- Version 1.0.3

**Comment by opa-oz** [comment]
@retani 
Thank you so much for the issue!
And sorry for _kinda_ unexpected behavioural.

**Comment by opa-oz** [comment]
@retani 
Thank you so much for bringing up the issue! And I apologize for the unexpected behavior. 

The issue is that when you override the default options, you need to specify the `base` yourself. After making these small modifications, you will see the expected result:
```js
import ehg, {getHash} from "https://cdn.skypack.dev/emoji-hash-gen@1.0.3";

const str = "Hello, world"


const nolength = getHash(str)
const length2 = getHash(str, {
    length: 2, 
    base: ehg.maxBase, // <====== that's base of default emoji-table
}) 
const length3 = getHash(str, {
    length: 3, 
    base: 62, // <====== the same value, but hardcoded
})                   
const length4 = getHash(str, {
    length: 4, 
    base: Object.keys(ehg.table).length,  // <====== or you can calculate it manually (also works with `useTable(myTable)`)
}) 

document.getElementById("nolength").innerHTML = nolength
document.getElementById("length2").innerHTML = length2
document.getElementById("length3").innerHTML = length3
document.getElementById("length4").innerHTML = length4
``` 
<img width="345" alt="Screenshot 2023-04-06 at 19 30 45" src="https://user-images.githubusercontent.com/34550675/230351752-a58671db-a757-4c18-9b59-2522050fa836.png">

**Comment by retani** [comment]
I see. Thanks for the explanation and quick reply!

**Comment by opa-oz** [comment]
Always welcome! 

Please feel free to open a new issue if anything is needed.
